
package interfazGrafica;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.*;
import java.util.Date;

public class JFrameSegundo extends javax.swing.JFrame {
    private logica.ListaEnlazada lista;         //Le pongo un atributo que sea lista
    private boolean banderaProducto;
    private Usuario user;
    private logica.ListaEnlazada listaCambios;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameSegundo.class.getName());
    
    
    public JFrameSegundo(ListaEnlazada lista, Usuario user, ListaEnlazada listaCambios) {
        this.lista = lista;                          //Inicializo lista
        this.banderaProducto=false;
        this.user = user;
        this.listaCambios = listaCambios;
        
        initComponents();
        actualizarTextArea();                       //Agrego en el textArea los productos ya cargados
        Icon imagenBienvenida = new ImageIcon(new ImageIcon (getClass().getResource("/Imagenes/bienvenida.jpg")).getImage()
        .getScaledInstance(imagenPrimerPanel.getWidth(), imagenPrimerPanel.getHeight(), 0));
        //imagenInicio.getWidth(), imagenInicio.getHeight()
        imagenPrimerPanel.setIcon(imagenBienvenida);
        this.setLocationRelativeTo(null);       //HACE QUE LA VENTANA ESTE CENTRADA   
        jScrollPane7.setVisible(false);
        inputNombreUsuario.setText(user.getNombre());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPrimero = new FondoPanel("/Imagenes/inicio.jpg");
        labelTituloPrimerPanel = new javax.swing.JLabel();
        novedadesPrimeraPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNovedades = new javax.swing.JTextArea();
        imagenPrimerPanel = new javax.swing.JLabel();
        JPanelSegundo = new FondoPanel("/Imagenes/ciudad.jpg");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busquedaSegundoPanel = new javax.swing.JTextField();
        botonBuscarSegundoPanel = new javax.swing.JButton();
        panelOculto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelNombreObjeto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInformacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jBotonDisminuirBoton = new javax.swing.JButton();
        JBotonAumentarStock = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaLista = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new FondoPanel("/Imagenes/ciudad.jpg");
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPrecioNuevProd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelStockNuevProd = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelInfoNuevProd = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabelMotivoNuevProd = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabelnombnuevProd = new javax.swing.JTextField();
        jPanel3 = new FondoPanel("/Imagenes/ciudad.jpg");
        jLabel11 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaCambios = new javax.swing.JTextArea();
        jPanel5 = new FondoPanel("/Imagenes/ciudad.jpg");
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        inputNombreUsuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        listaDesplegable = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buttonObjeto1 = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        inputObjeto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        buttonObjeto2 = new javax.swing.JToggleButton();
        buttonObjeto4 = new javax.swing.JToggleButton();
        buttonObjeto3 = new javax.swing.JToggleButton();
        butoonStock1 = new javax.swing.JToggleButton();
        butoonStock2 = new javax.swing.JToggleButton();
        butoonStock3 = new javax.swing.JToggleButton();
        butoonStock4 = new javax.swing.JToggleButton();
        butonNotificaciones1 = new javax.swing.JToggleButton();
        butonNotificaciones2 = new javax.swing.JToggleButton();
        butonNotificaciones3 = new javax.swing.JToggleButton();
        butonNotificaciones4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(93, 37, 37));
        jTabbedPane.setForeground(new java.awt.Color(252, 242, 242));
        jTabbedPane.setPreferredSize(new java.awt.Dimension(1243, 684));
        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });

        jPanelPrimero.setBackground(new java.awt.Color(0, 0, 0));

        labelTituloPrimerPanel.setBackground(new java.awt.Color(73, 33, 63));
        labelTituloPrimerPanel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        labelTituloPrimerPanel.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloPrimerPanel.setText("BIENVENIDO A LA PLATAFORMA DE LA EMPRESA");
        labelTituloPrimerPanel.setOpaque(true);

        novedadesPrimeraPanel.setBackground(new java.awt.Color(67, 48, 48));
        novedadesPrimeraPanel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        novedadesPrimeraPanel.setForeground(new java.awt.Color(255, 255, 255));
        novedadesPrimeraPanel.setText("            ULTIMAS NOVEDADES !!!");
        novedadesPrimeraPanel.setOpaque(true);

        jTextAreaNovedades.setEditable(false);
        jTextAreaNovedades.setBackground(new java.awt.Color(181, 169, 169));
        jTextAreaNovedades.setColumns(20);
        jTextAreaNovedades.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jTextAreaNovedades.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaNovedades.setLineWrap(true);
        jTextAreaNovedades.setRows(5);
        jTextAreaNovedades.setText("Equipo de Operacion de control y calidad:\n\nLa plataforma entrara en periodo de mantenimiento entre los dias 20/03/2026 - 26/03/2026. Por favor mantener todos los recaudos necesarios para evitar inconvenientes. Gracias !!!\n\nEquipo Informatico.");
        jTextAreaNovedades.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaNovedades);

        imagenPrimerPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPrimerPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrimeroLayout = new javax.swing.GroupLayout(jPanelPrimero);
        jPanelPrimero.setLayout(jPanelPrimeroLayout);
        jPanelPrimeroLayout.setHorizontalGroup(
            jPanelPrimeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimeroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelPrimeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrimeroLayout.createSequentialGroup()
                        .addComponent(labelTituloPrimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addGroup(jPanelPrimeroLayout.createSequentialGroup()
                        .addGroup(jPanelPrimeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novedadesPrimeraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenPrimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelPrimeroLayout.setVerticalGroup(
            jPanelPrimeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimeroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTituloPrimerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanelPrimeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrimeroLayout.createSequentialGroup()
                        .addComponent(novedadesPrimeraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addComponent(imagenPrimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("PANTALLA DE INICIO", jPanelPrimero);

        JPanelSegundo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                JPanelSegundoComponentShown(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(49, 14, 45));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLES DE STOCK");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(94, 17, 98));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                      LISTA DE PRODUCTOS");
        jLabel2.setOpaque(true);

        busquedaSegundoPanel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        busquedaSegundoPanel.addActionListener(this::busquedaSegundoPanelActionPerformed);

        botonBuscarSegundoPanel.setBackground(new java.awt.Color(51, 0, 51));
        botonBuscarSegundoPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscarSegundoPanel.setForeground(new java.awt.Color(204, 204, 205));
        botonBuscarSegundoPanel.setText("Buscar");
        botonBuscarSegundoPanel.addActionListener(this::botonBuscarSegundoPanelActionPerformed);

        panelOculto.setBackground(new java.awt.Color(177, 132, 181));
        panelOculto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOculto.setForeground(new java.awt.Color(149, 37, 155));
        panelOculto.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRE DEL OBJETO:");

        labelNombreObjeto.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelNombreObjeto.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CANTIDAD DE STOCK:");

        textAreaInformacion.setEditable(false);
        textAreaInformacion.setBackground(new java.awt.Color(221, 198, 198));
        textAreaInformacion.setColumns(20);
        textAreaInformacion.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        textAreaInformacion.setForeground(new java.awt.Color(0, 0, 0));
        textAreaInformacion.setLineWrap(true);
        textAreaInformacion.setRows(5);
        textAreaInformacion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textAreaInformacion);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INFORMACION:");

        jLabelStock.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(0, 0, 0));

        jBotonDisminuirBoton.setBackground(new java.awt.Color(66, 19, 33));
        jBotonDisminuirBoton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jBotonDisminuirBoton.setForeground(new java.awt.Color(0, 0, 0));
        jBotonDisminuirBoton.setText("DISMINIUR STOCK");
        jBotonDisminuirBoton.setEnabled(false);
        jBotonDisminuirBoton.addActionListener(this::jBotonDisminuirBotonActionPerformed);

        JBotonAumentarStock.setBackground(new java.awt.Color(58, 10, 53));
        JBotonAumentarStock.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JBotonAumentarStock.setForeground(new java.awt.Color(0, 0, 0));
        JBotonAumentarStock.setText("AUMENTAR STOCK");
        JBotonAumentarStock.setEnabled(false);
        JBotonAumentarStock.addActionListener(this::JBotonAumentarStockActionPerformed);

        javax.swing.GroupLayout panelOcultoLayout = new javax.swing.GroupLayout(panelOculto);
        panelOculto.setLayout(panelOcultoLayout);
        panelOcultoLayout.setHorizontalGroup(
            panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOcultoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOcultoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOcultoLayout.createSequentialGroup()
                                .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addComponent(labelNombreObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelOcultoLayout.createSequentialGroup()
                        .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOcultoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(16, 16, 16))))
            .addGroup(panelOcultoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JBotonAumentarStock)
                .addGap(18, 18, 18)
                .addComponent(jBotonDisminuirBoton)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelOcultoLayout.setVerticalGroup(
            panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOcultoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(labelNombreObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOcultoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOcultoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBotonAumentarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonDisminuirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel12.setBackground(new java.awt.Color(57, 16, 56));
        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Realizar la busqueda de un objeto:");
        jLabel12.setOpaque(true);

        textAreaLista.setEditable(false);
        textAreaLista.setBackground(new java.awt.Color(191, 136, 195));
        textAreaLista.setColumns(20);
        textAreaLista.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        textAreaLista.setForeground(new java.awt.Color(0, 0, 0));
        textAreaLista.setRows(5);
        jScrollPane6.setViewportView(textAreaLista);

        jLabel28.setBackground(new java.awt.Color(49, 14, 45));
        jLabel28.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("                   INFORMACION ");
        jLabel28.setOpaque(true);

        javax.swing.GroupLayout JPanelSegundoLayout = new javax.swing.GroupLayout(JPanelSegundo);
        JPanelSegundo.setLayout(JPanelSegundoLayout);
        JPanelSegundoLayout.setHorizontalGroup(
            JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSegundoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelSegundoLayout.createSequentialGroup()
                        .addComponent(busquedaSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addGroup(JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        JPanelSegundoLayout.setVerticalGroup(
            JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSegundoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelSegundoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelSegundoLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(panelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(JPanelSegundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarSegundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTabbedPane.addTab("CONTROL DE STOCK", JPanelSegundo);

        jLabel7.setBackground(new java.awt.Color(49, 14, 45));
        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 252, 252));
        jLabel7.setText("AGREGADO DE NUEVOS PRODUCTO");
        jLabel7.setOpaque(true);

        jPanel7.setBackground(new java.awt.Color(177, 132, 181));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NOMBRE DEL PRODUCTO:");

        jLabelPrecioNuevProd.setBackground(new java.awt.Color(177, 132, 181));
        jLabelPrecioNuevProd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelPrecioNuevProd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecioNuevProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPrecioNuevProd.addActionListener(this::jLabelPrecioNuevProdActionPerformed);

        jLabel9.setBackground(new java.awt.Color(177, 132, 181));
        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CANTIDAD DE STOCK:");

        jLabelStockNuevProd.setBackground(new java.awt.Color(177, 132, 181));
        jLabelStockNuevProd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelStockNuevProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setBackground(new java.awt.Color(177, 132, 181));
        jLabel29.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("INFORMACION DEL OBJETO:");

        jLabelInfoNuevProd.setBackground(new java.awt.Color(177, 132, 181));
        jLabelInfoNuevProd.setColumns(20);
        jLabelInfoNuevProd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelInfoNuevProd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNuevProd.setRows(5);
        jLabelInfoNuevProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jLabelInfoNuevProd);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MOTIVO DEL AGREGADO:");

        jLabelMotivoNuevProd.setBackground(new java.awt.Color(177, 132, 181));
        jLabelMotivoNuevProd.setColumns(20);
        jLabelMotivoNuevProd.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelMotivoNuevProd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMotivoNuevProd.setRows(5);
        jLabelMotivoNuevProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(jLabelMotivoNuevProd);

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR OBJETO");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel30.setBackground(new java.awt.Color(177, 132, 181));
        jLabel30.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("PRECIO DEL PRODUCTO");

        jLabelnombnuevProd.setBackground(new java.awt.Color(177, 132, 181));
        jLabelnombnuevProd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelnombnuevProd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelnombnuevProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelnombnuevProd.setCaretColor(new java.awt.Color(0, 0, 0));
        jLabelnombnuevProd.addActionListener(this::jLabelnombnuevProdActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStockNuevProd)
                            .addComponent(jLabelnombnuevProd)
                            .addComponent(jLabelPrecioNuevProd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnombnuevProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecioNuevProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStockNuevProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("CONTROL DE OBJETOS", jPanel2);

        jLabel11.setBackground(new java.awt.Color(97, 22, 71));
        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OPCIONES A REALIZAR:");
        jLabel11.setOpaque(true);

        jLabel121.setBackground(new java.awt.Color(49, 14, 45));
        jLabel121.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 255, 255));
        jLabel121.setText("CENTRO DE CONTROL DE NOTIFICACIONES");
        jLabel121.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(97, 22, 71));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 124, 188)));

        jButton2.setBackground(new java.awt.Color(189, 15, 102));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ENVIAR CORREO");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(189, 15, 102));
        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BORRAR NOVEDADES");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(189, 15, 102));
        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("AGREGAR NOVEDADES");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(189, 15, 102));
        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("MOSTRAR ULTIMOS CAMBIOS");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        textAreaCambios.setEditable(false);
        textAreaCambios.setBackground(new java.awt.Color(97, 22, 71));
        textAreaCambios.setColumns(20);
        textAreaCambios.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        textAreaCambios.setForeground(new java.awt.Color(255, 255, 255));
        textAreaCambios.setRows(5);
        jScrollPane7.setViewportView(textAreaCambios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jTabbedPane.addTab("CONTROL DE MENSAJES", jPanel3);

        jLabel13.setBackground(new java.awt.Color(49, 14, 45));
        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ESTA ENCUESTA DEBE RESPONDERSE SIEMPRE AL FINALIZAR EL DIA");
        jLabel13.setOpaque(true);

        jPanel6.setBackground(new java.awt.Color(122, 51, 97));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("NOMBRE DEL USUARIO:");

        inputNombreUsuario.setEditable(false);
        inputNombreUsuario.setBackground(new java.awt.Color(129, 26, 93));
        inputNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        inputNombreUsuario.addActionListener(this::inputNombreUsuarioActionPerformed);

        jLabel15.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("SELECCIONAR CARGO:");

        listaDesplegable.setBackground(new java.awt.Color(189, 15, 102));
        listaDesplegable.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        listaDesplegable.setForeground(new java.awt.Color(255, 255, 255));
        listaDesplegable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Control de Stock", "Control de Objetos", "Administrador", "Control de Notificaciones" }));
        listaDesplegable.addActionListener(this::listaDesplegableActionPerformed);

        jLabel16.setBackground(new java.awt.Color(189, 15, 102));
        jLabel16.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CONTROL DE OBJETOS");
        jLabel16.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Se han agregados nuevos objetos?");

        buttonObjeto1.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup1.add(buttonObjeto1);
        buttonObjeto1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        buttonObjeto1.setText("SI");
        buttonObjeto1.setEnabled(false);
        buttonObjeto1.addActionListener(this::buttonObjeto1ActionPerformed);

        jLabel18.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Ingresar cantidad de objetos agregados:");

        inputObjeto.setBackground(new java.awt.Color(129, 26, 93));
        inputObjeto.setForeground(new java.awt.Color(255, 255, 255));
        inputObjeto.setOpaque(true);
        inputObjeto.addActionListener(this::inputObjetoActionPerformed);

        jLabel19.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Se han eliminado objetos?");

        jLabel20.setBackground(new java.awt.Color(189, 15, 102));
        jLabel20.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CONTROL DE STOCK");
        jLabel20.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(191, 136, 195));
        jSeparator1.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Se ha llegado al stock 0? ");

        jLabel22.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Ha habido un aumento de mas de 10.000?");

        jLabel23.setBackground(new java.awt.Color(189, 15, 102));
        jLabel23.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CONTROL DE NOTIFICACIONES");
        jLabel23.setOpaque(true);

        jLabel24.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nuevo mensajes de Novedades?");

        jLabel25.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Se han enviado un correo electronico?");

        jLabel26.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("AGREGAR COMENTARIOS:");

        jTextArea4.setBackground(new java.awt.Color(191, 136, 195));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jButton6.setBackground(new java.awt.Color(49, 14, 45));
        jButton6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ENVIAR");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        buttonObjeto2.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup1.add(buttonObjeto2);
        buttonObjeto2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        buttonObjeto2.setText("NO");
        buttonObjeto2.setEnabled(false);
        buttonObjeto2.addActionListener(this::buttonObjeto2ActionPerformed);

        buttonObjeto4.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup2.add(buttonObjeto4);
        buttonObjeto4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        buttonObjeto4.setText("NO");
        buttonObjeto4.setEnabled(false);

        buttonObjeto3.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup2.add(buttonObjeto3);
        buttonObjeto3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        buttonObjeto3.setText("SI");
        buttonObjeto3.setEnabled(false);
        buttonObjeto3.addActionListener(this::buttonObjeto3ActionPerformed);

        butoonStock1.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup3.add(butoonStock1);
        butoonStock1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butoonStock1.setText("SI");
        butoonStock1.setEnabled(false);

        butoonStock2.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup3.add(butoonStock2);
        butoonStock2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butoonStock2.setText("NO");
        butoonStock2.setEnabled(false);
        butoonStock2.addActionListener(this::butoonStock2ActionPerformed);

        butoonStock3.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup4.add(butoonStock3);
        butoonStock3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butoonStock3.setText("SI");
        butoonStock3.setEnabled(false);
        butoonStock3.addActionListener(this::butoonStock3ActionPerformed);

        butoonStock4.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup4.add(butoonStock4);
        butoonStock4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butoonStock4.setText("NO");
        butoonStock4.setEnabled(false);
        butoonStock4.addActionListener(this::butoonStock4ActionPerformed);

        butonNotificaciones1.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup5.add(butonNotificaciones1);
        butonNotificaciones1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butonNotificaciones1.setText("SI");
        butonNotificaciones1.setEnabled(false);

        butonNotificaciones2.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup5.add(butonNotificaciones2);
        butonNotificaciones2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butonNotificaciones2.setText("NO");
        butonNotificaciones2.setEnabled(false);
        butonNotificaciones2.addActionListener(this::butonNotificaciones2ActionPerformed);

        butonNotificaciones3.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup6.add(butonNotificaciones3);
        butonNotificaciones3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butonNotificaciones3.setText("SI");
        butonNotificaciones3.setEnabled(false);

        butonNotificaciones4.setBackground(new java.awt.Color(189, 15, 102));
        buttonGroup6.add(butonNotificaciones4);
        butonNotificaciones4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        butonNotificaciones4.setText("NO");
        butonNotificaciones4.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonObjeto3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonObjeto4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputObjeto))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonObjeto1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonObjeto2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listaDesplegable, 0, 1, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(butoonStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(butoonStock3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(butoonStock4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(butonNotificaciones3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(butonNotificaciones4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(butonNotificaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(butonNotificaciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(butoonStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(14, 14, 14))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butoonStock1)
                            .addComponent(butoonStock2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaDesplegable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonObjeto1)
                            .addComponent(buttonObjeto2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(inputObjeto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonObjeto4)
                            .addComponent(buttonObjeto3))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel27))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butoonStock3)
                            .addComponent(butoonStock4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(butonNotificaciones1)
                                .addComponent(butonNotificaciones2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonNotificaciones3)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonNotificaciones4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("ENCUESTA DE CONTROL", jPanel5);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDesplegableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDesplegableActionPerformed
        String cargo = (String) listaDesplegable.getSelectedItem();
        switch(cargo){
            case "Control de Objetos":
                buttonObjeto1.setEnabled(true);
                buttonObjeto2.setEnabled(true);
                buttonObjeto3.setEnabled(true);
                buttonObjeto4.setEnabled(true);
                inputObjeto.setEnabled(true);
                butoonStock1.setEnabled(false);
                butoonStock2.setEnabled(false);
                butoonStock3.setEnabled(false);
                butoonStock4.setEnabled(false);
                butonNotificaciones1.setEnabled(false);
                butonNotificaciones2.setEnabled(false);
                butonNotificaciones3.setEnabled(false);
                butonNotificaciones4.setEnabled(false);
                break;
            case "Control de Stock":
                buttonObjeto1.setEnabled(false);
                buttonObjeto2.setEnabled(false);
                buttonObjeto3.setEnabled(false);
                buttonObjeto4.setEnabled(false);
                inputObjeto.setEnabled(false);
                butoonStock1.setEnabled(true);
                butoonStock2.setEnabled(true);
                butoonStock3.setEnabled(true);
                butoonStock4.setEnabled(true);
                butonNotificaciones1.setEnabled(false);
                butonNotificaciones2.setEnabled(false);
                butonNotificaciones3.setEnabled(false);
                butonNotificaciones4.setEnabled(false);
                break;
            case "Control de Notificaciones":
                buttonObjeto1.setEnabled(false);
                buttonObjeto2.setEnabled(false);
                buttonObjeto3.setEnabled(false);
                buttonObjeto4.setEnabled(false);
                inputObjeto.setEnabled(false);
                butoonStock1.setEnabled(false);
                butoonStock2.setEnabled(false);
                butoonStock3.setEnabled(false);
                butoonStock4.setEnabled(false);
                butonNotificaciones1.setEnabled(true);
                butonNotificaciones2.setEnabled(true);
                butonNotificaciones3.setEnabled(true);
                butonNotificaciones4.setEnabled(true);
                break;
            case "Administrador":
                buttonObjeto1.setEnabled(true);
                buttonObjeto2.setEnabled(true);
                buttonObjeto3.setEnabled(true);
                buttonObjeto4.setEnabled(true);
                inputObjeto.setEnabled(true);
                butoonStock1.setEnabled(true);
                butoonStock2.setEnabled(true);
                butoonStock3.setEnabled(true);
                butoonStock4.setEnabled(true);
                butonNotificaciones1.setEnabled(true);
                butonNotificaciones2.setEnabled(true);
                butonNotificaciones3.setEnabled(true);
                butonNotificaciones4.setEnabled(true);
                break;
            
        }
        listaDesplegable.setEnabled(false);

    }//GEN-LAST:event_listaDesplegableActionPerformed

    private void imagenPrimerPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPrimerPanelComponentResized
        
    }//GEN-LAST:event_imagenPrimerPanelComponentResized

    private void botonBuscarSegundoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarSegundoPanelActionPerformed

        String ProductoBuscar = busquedaSegundoPanel.getText();
        //Realizo la busqueda del segundo producto
            Producto productoBuscado = busqueda(lista, ProductoBuscar);
            if (productoBuscado!=null){
                labelNombreObjeto.setText(productoBuscado.getNombre());
                textAreaInformacion.setText(productoBuscado.toString());
                jLabelStock.setText(Integer.toString(productoBuscado.getStock()));
                JBotonAumentarStock.setEnabled(true);
                jBotonDisminuirBoton.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "PRODUCTO NO ENCONTRADO EN LA LISTA", "ERROR",HEIGHT);
            }
        
    }//GEN-LAST:event_botonBuscarSegundoPanelActionPerformed

    private void busquedaSegundoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaSegundoPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaSegundoPanelActionPerformed

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void JPanelSegundoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JPanelSegundoComponentShown
       /* //EVENTOS AL ESTAR EL USUARIO EN LA PANTALLA
        Nodo puntero = lista.getCabeza();
        while (puntero!=null){
            textAreaLista.append(puntero.getDato().getNombre() + "\n");
            puntero = puntero.getSiguiente();
        }*/
    }//GEN-LAST:event_JPanelSegundoComponentShown

    private void JBotonAumentarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonAumentarStockActionPerformed
        //Debo realizar la busqueda nuevamente
        Producto productoBuscado = busqueda(lista, busquedaSegundoPanel.getText());
        productoBuscado.setStock(productoBuscado.getStock()+1);
        jLabelStock.setText(Integer.toString(productoBuscado.getStock()));
    }//GEN-LAST:event_JBotonAumentarStockActionPerformed

    private void jBotonDisminuirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDisminuirBotonActionPerformed
        Producto productoBuscado = busqueda(lista, busquedaSegundoPanel.getText());
        productoBuscado.setStock(productoBuscado.getStock()-1);
        jLabelStock.setText(Integer.toString(productoBuscado.getStock()));
    }//GEN-LAST:event_jBotonDisminuirBotonActionPerformed

    private void jLabelPrecioNuevProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelPrecioNuevProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrecioNuevProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreNuevProd = jLabelnombnuevProd.getText();
        Date fechaActual = new Date();
        
        //Verificacion de datos
        try{
            int PrecioNuevProd = Integer.parseInt(jLabelPrecioNuevProd.getText());
            int StockNuevProd = Integer.parseInt(jLabelStockNuevProd.getText());
            
            if(PrecioNuevProd<=0 || StockNuevProd<=0){
                JOptionPane.showMessageDialog(this, "El producto no puede tener valores asignados en 0 o negativos", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;         //Asi sale del try
            }
            //REALIZAMOS LA BUSQUEDA DEL PRODUCTO PARA VER SI ESTA EN LA LISTA
            
            Producto productoBusqueda = busqueda(lista, nombreNuevProd);
            if (productoBusqueda==null){
                Producto nuevoProducto = new Producto(nombreNuevProd,PrecioNuevProd,StockNuevProd,jLabelInfoNuevProd.getText(),fechaActual);
                lista.insertar_comienzo(nuevoProducto);
                
                CambioRealizado nuevoCambio = new CambioRealizado(fechaActual,user,"Se ha agregado un nuevo producto. " + nuevoProducto.toString());
                listaCambios.insertar_comienzo(nuevoCambio);
                
                JOptionPane.showMessageDialog(this, "PRODUCTO AGREGADO CON EXITO", "Informacion",JOptionPane.INFORMATION_MESSAGE);
                actualizarTextArea();
                jLabelnombnuevProd.setText("");
                jLabelPrecioNuevProd.setText("");
                jLabelStockNuevProd.setText("");
                jLabelInfoNuevProd.setText("");
                jLabelMotivoNuevProd.setText("");
                
            }else{
                JOptionPane.showMessageDialog(this, "EL PRODUCTO YA ESTA REGISTRADO", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {
        // Si el precio, la cantidad, O el peso tienen letras, el código salta aquí.
        JOptionPane.showMessageDialog(this, "Asegúrate de que todos los campos contengan solo números válidos.", "ERROR", JOptionPane.ERROR_MESSAGE);
}
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelnombnuevProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelnombnuevProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelnombnuevProdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!listaCambios.listaVacia()){
            jScrollPane7.setVisible(true);
            // Estas dos líneas obligan a la pantalla a mostrar el cuadro AL INSTANTE
            textAreaCambios.setText(mostrarText(listaCambios));
            jPanel3.revalidate();
            jPanel3.repaint();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "No se han realizado cambios recientemente", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);           }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Date fechaActual = new Date();
        /*String TextoNovedades = jTextAreaNovedades.getText();
        String NuevoTextoNoveda = javax.swing.JOptionPane.showInputDialog(this, "Ingresar nueva Novedad", "TEXTO NOVEDAD", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (NuevoTextoNoveda != null && !NuevoTextoNoveda.trim().isEmpty()) {
            jTextAreaNovedades.append("\n\n" + NuevoTextoNoveda + "\n Atentamente Equipo de Control y Calidad");
            javax.swing.JOptionPane.showConfirmDialog(this, "Se ha actualizado el perfil de novedades correctamente", "OPERACION EXITOSA", javax.swing.JOptionPane.OK_OPTION);
        }*/

        //FORMA MAS ELABORADA

        // Fabricamos un JTextArea a medida
        javax.swing.JTextArea areaTexto = new javax.swing.JTextArea(10, 30);
        areaTexto.setLineWrap(true); // Hace que el texto baje si choca con el borde derecho
        areaTexto.setWrapStyleWord(true); // Evita que las palabras se corten por la mitad

        // Lo metemos en un JScrollPane
        javax.swing.JScrollPane panelConScroll = new javax.swing.JScrollPane(areaTexto);

        int opcionElegida = javax.swing.JOptionPane.showConfirmDialog(this,
            panelConScroll,
            "Escribir la Nueva Novedad:",
            javax.swing.JOptionPane.OK_CANCEL_OPTION,       // Le ordena a Java que dibuje dos botones en la parte de abajo de la ventana: uno que diga Aceptar y otro que diga Cancelar
            javax.swing.JOptionPane.PLAIN_MESSAGE);         // Le dice a java que no ponga ningun icono

        // Si el usuario apretó el botón "Aceptar" (OK_OPTION)
        if (opcionElegida == javax.swing.JOptionPane.OK_OPTION) {

            // Sacamos el texto con todos sus saltos de línea (Enters)
            String NuevoTextoNoveda = areaTexto.getText();

            if (!NuevoTextoNoveda.trim().isEmpty()) {

                jTextAreaNovedades.append("\n\n ------------------------------------------------------------------------------------- \n" + NuevoTextoNoveda + "\n Atentamente: " + user.getNombre() + " parte del Control y Calidad");

                javax.swing.JOptionPane.showMessageDialog(this, "Mensaje actualizado con éxito", "OPERACION EXITOSA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                CambioRealizado nuevCambio = new CambioRealizado (fechaActual,user,"Se ha actualizado la tabla de novedades, mensaje:" + NuevoTextoNoveda);
                listaCambios.insertar_comienzo(nuevCambio);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se puede enviar mensajes vacios", "ADVERTENCIA", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "Seguro que desea borrar todas las novedades?", "ADVERTENCIA", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        Date fechaActual = new Date();
        if (opcion == javax.swing.JOptionPane.OK_OPTION) {
            jTextAreaNovedades.setText("");
            javax.swing.JOptionPane.showConfirmDialog(this, "Novedades Borradas con exito", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            CambioRealizado nvCambio = new CambioRealizado (fechaActual,user,"Se ha borrado las novedades");
            lista.insertar_comienzo(nvCambio);
        }else{
            javax.swing.JOptionPane.showConfirmDialog(this, "Se ha rechazado el borrado", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String destinatario = "contactoempresa@gmail.com";
            String asunto = "Informe sobre Consulta de Productos";

            String asuntoCodificado = java.net.URLEncoder.encode(asunto, "UTF-8").replace("+", "%20");

            /*
            view=cm: Significa "Compose Message" (Redactar mensaje)
            to=:  Le avisa a Gmail a quién se lo vas a mandar
            su=: Significa "Subject" (Asunto)
            */

            String enlaceGmail = "https://mail.google.com/mail/?view=cm&to=" + destinatario + "&su=" + asuntoCodificado;
            // crea un nuevo objeto que representa una dirección web o enlace (URI) utilizando un texto almacenado en la variable enlaceGmail

            java.net.URI uri = new java.net.URI(enlaceGmail);

            //Verificamos si se puede
            if (java.awt.Desktop.isDesktopSupported() && java.awt.Desktop.getDesktop().isSupported(java.awt.Desktop.Action.BROWSE)) {

                java.awt.Desktop.getDesktop().browse(uri);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Tu computadora no permite abrir el navegador desde Java.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar abrir Gmail.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inputNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreUsuarioActionPerformed
           
    }//GEN-LAST:event_inputNombreUsuarioActionPerformed

    private void buttonObjeto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObjeto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonObjeto2ActionPerformed

    private void inputObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputObjetoActionPerformed

    private void butoonStock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoonStock2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butoonStock2ActionPerformed

    private void butoonStock3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoonStock3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butoonStock3ActionPerformed

    private void butoonStock4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoonStock4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butoonStock4ActionPerformed

    private void butonNotificaciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNotificaciones2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonNotificaciones2ActionPerformed

    private void buttonObjeto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObjeto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonObjeto3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String cargoElegido = (String) listaDesplegable.getSelectedItem();
        String cadenaInforme = "Usuario: " + user.getNombre() + " con el rol de: " + cargoElegido + "\n\n";
        EncuestaUsuario encuesta = new EncuestaUsuario();
        
        if (cargoElegido.equals("Control de Stock") || cargoElegido.equals("Administrador")) {

            cadenaInforme += "--- AREA DE STOCK ---\n";
            cadenaInforme += "Se han agregado objetos?: ";
            if (buttonObjeto1.isSelected()) {
                cadenaInforme += "SI. Cantidad: " + inputObjeto.getText() + "\n";
            } else if (buttonObjeto2.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }

            cadenaInforme += "Se han eliminado Objetos?: ";
            if (buttonObjeto3.isSelected()) {
                cadenaInforme += "SI\n";
            } else if (buttonObjeto4.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }
        }

        if (cargoElegido.equals("Control de Objetos") || cargoElegido.equals("Administrador")) {

            cadenaInforme += "\n--- AREA DE OBJETOS ---\n";
            cadenaInforme += "Se ha llegado al stock 0?: ";
            if (butoonStock1.isSelected()) {
                cadenaInforme += "SI\n"; 
            } else if (butoonStock2.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }
            cadenaInforme += "Ha habido un aumento de mas de 10.000?: ";
            if (butoonStock3.isSelected()) {
                cadenaInforme += "SI\n";
            } else if (butoonStock4.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }
        }

        if (cargoElegido.equals("Control de Notificaciones") || cargoElegido.equals("Administrador")) {

            cadenaInforme += "\n--- AREA DE NOTIFICACIONES ---\n";
            cadenaInforme += "Nuevo Mensaje de novedades?: ";
            if (butonNotificaciones1.isSelected()) {
                cadenaInforme += "SI\n"; 
            } else if (butonNotificaciones2.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }

            cadenaInforme += "Se ha enviado un correo Electronico?: ";
            if (butonNotificaciones3.isSelected()) {
                cadenaInforme += "SI\n";
            } else if (butonNotificaciones4.isSelected()) {
                cadenaInforme += "NO\n";
            } else {
                cadenaInforme += "Sin responder\n";
            }
        }
        cadenaInforme += "Comentarios: " + jTextArea4.getText()+ "\n";
        cadenaInforme += "\n--- ULTIMOS CAMBIOS REALIZADOS POR EL USUARIO ---\n" + mostrarText(listaCambios);
        System.out.println(cadenaInforme);
        encuesta.escribirArchivo(cadenaInforme);
        javax.swing.JOptionPane.showMessageDialog(this, "Encuesta Enviada con Exito, cerrando Programa", "Operacion Realizada", javax.swing.JOptionPane.WARNING_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buttonObjeto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObjeto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonObjeto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotonAumentarStock;
    private javax.swing.JPanel JPanelSegundo;
    private javax.swing.JButton botonBuscarSegundoPanel;
    private javax.swing.JTextField busquedaSegundoPanel;
    private javax.swing.JToggleButton butonNotificaciones1;
    private javax.swing.JToggleButton butonNotificaciones2;
    private javax.swing.JToggleButton butonNotificaciones3;
    private javax.swing.JToggleButton butonNotificaciones4;
    private javax.swing.JToggleButton butoonStock1;
    private javax.swing.JToggleButton butoonStock2;
    private javax.swing.JToggleButton butoonStock3;
    private javax.swing.JToggleButton butoonStock4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JToggleButton buttonObjeto1;
    private javax.swing.JToggleButton buttonObjeto2;
    private javax.swing.JToggleButton buttonObjeto3;
    private javax.swing.JToggleButton buttonObjeto4;
    private javax.swing.JLabel imagenPrimerPanel;
    private javax.swing.JTextField inputNombreUsuario;
    private javax.swing.JTextField inputObjeto;
    private javax.swing.JButton jBotonDisminuirBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jLabelInfoNuevProd;
    private javax.swing.JTextArea jLabelMotivoNuevProd;
    private javax.swing.JTextField jLabelPrecioNuevProd;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JTextField jLabelStockNuevProd;
    private javax.swing.JTextField jLabelnombnuevProd;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelPrimero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextAreaNovedades;
    private javax.swing.JLabel labelNombreObjeto;
    private javax.swing.JLabel labelTituloPrimerPanel;
    private javax.swing.JComboBox<String> listaDesplegable;
    private javax.swing.JLabel novedadesPrimeraPanel;
    private javax.swing.JPanel panelOculto;
    private javax.swing.JTextArea textAreaCambios;
    private javax.swing.JTextArea textAreaInformacion;
    private javax.swing.JTextArea textAreaLista;
    // End of variables declaration//GEN-END:variables
    
    
    class FondoPanel extends JPanel {
        private Image imagen;

        public FondoPanel(String ruta) {
            this.setOpaque(false); 

            this.imagen = new ImageIcon(getClass().getResource(ruta)).getImage();
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); 
            // Dibuja la foto adaptándose al panel
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    private void actualizarTextArea (){
        String textCompleto = mostrarInfoCompleta(lista);
        textAreaLista.setText(textCompleto);
    }
   //Metodo de la Lista Enlazada
    public Producto busqueda(ListaEnlazada Lista, String nombreProducto){
            if (!Lista.listaVacia()){
                Nodo puntero = Lista.getCabeza();
                while(puntero!=null){
                    Producto ProductoLista = (Producto) puntero.getDato();
                    if (ProductoLista.getNombre().equals(nombreProducto)){
                        return ((Producto) puntero.getDato());
                    }puntero = puntero.getSiguiente();
                }
                return (null);
            }else{
                System.out.println("Error lista vacia");
                return null;
            }
        }
    public String mostrarInfoCompleta(ListaEnlazada lista){
        Nodo ref = lista.getCabeza();
        String text = "";
        
        while(ref!=null){
            Producto elementoLista = (Producto) ref.getDato();
            text += elementoLista.getNombre() + "\n";
            ref = ref.getSiguiente();
        }
    return text;
    }
    public String mostrarText(ListaEnlazada lista){
                Nodo referencia = lista.getCabeza();
                String texto = "";
                while (referencia!=null){
                    CambioRealizado ultimoCambio = (CambioRealizado) referencia.getDato();
                    texto += "\n" + ultimoCambio.toString() + "\n";
                    referencia=referencia.getSiguiente();
                }
                return texto;
        }
}

    
